// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" form:"name" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

type HelloResp struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"content"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResp) Reset()         { *m = HelloResp{} }
func (m *HelloResp) String() string { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()    {}
func (*HelloResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *HelloResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResp.Unmarshal(m, b)
}
func (m *HelloResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResp.Marshal(b, m, deterministic)
}
func (m *HelloResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResp.Merge(m, src)
}
func (m *HelloResp) XXX_Size() int {
	return xxx_messageInfo_HelloResp.Size(m)
}
func (m *HelloResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HelloReq)(nil), "app.service.v1.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "app.service.v1.HelloResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4e, 0x32, 0x41,
	0x14, 0xc5, 0x97, 0x0f, 0x3e, 0x81, 0xf1, 0x4f, 0x31, 0x85, 0x81, 0xd5, 0x2c, 0x64, 0x8c, 0x89,
	0x8d, 0xb3, 0x11, 0x0b, 0x13, 0x3a, 0x21, 0x24, 0x96, 0x06, 0x3a, 0x1b, 0x33, 0x2c, 0x77, 0xd7,
	0x49, 0x66, 0x67, 0x86, 0xdd, 0x81, 0xc4, 0xd6, 0x57, 0xb0, 0xb1, 0xf5, 0x6d, 0x28, 0x4d, 0xec,
	0x89, 0xa2, 0x95, 0xa5, 0x4f, 0x60, 0x98, 0xdd, 0x8d, 0xb1, 0xa0, 0x9b, 0x7b, 0x7e, 0xf7, 0x9c,
	0xdc, 0x33, 0xa8, 0xce, 0x34, 0xa7, 0x3a, 0x51, 0x46, 0xe1, 0x3d, 0xa6, 0x35, 0x4d, 0x21, 0x99,
	0xf3, 0x00, 0xe8, 0xfc, 0xcc, 0x3d, 0x8d, 0xb8, 0xb9, 0x9b, 0x8d, 0x69, 0xa0, 0x62, 0x3f, 0x52,
	0x91, 0xf2, 0xed, 0xda, 0x78, 0x16, 0xda, 0xc9, 0x0e, 0xf6, 0x95, 0xd9, 0xdd, 0x83, 0x48, 0xa9,
	0x48, 0xc0, 0xef, 0x16, 0xc4, 0xda, 0xdc, 0xe7, 0xf0, 0x30, 0x87, 0x4c, 0x73, 0x9f, 0x49, 0xa9,
	0x0c, 0x33, 0x5c, 0xc9, 0x34, 0xa3, 0xa4, 0x8f, 0x6a, 0x57, 0x20, 0x84, 0x1a, 0xc2, 0x14, 0x5f,
	0xa0, 0x8a, 0x64, 0x31, 0x34, 0x4a, 0xed, 0xd2, 0x49, 0xbd, 0x77, 0xf4, 0xbd, 0x6c, 0xb5, 0x42,
	0x95, 0xc4, 0x5d, 0xb2, 0x56, 0x49, 0x7b, 0xce, 0x04, 0x9f, 0x30, 0x03, 0x5d, 0x92, 0xc0, 0x74,
	0xc6, 0x13, 0x98, 0x90, 0xa1, 0x35, 0x90, 0x0e, 0xaa, 0xe7, 0x21, 0xa9, 0xc6, 0xc7, 0xa8, 0xda,
	0x57, 0xd2, 0x80, 0x34, 0x79, 0xd0, 0xf6, 0xd7, 0xb2, 0x55, 0x0d, 0x32, 0x69, 0x58, 0xb0, 0xce,
	0x73, 0x09, 0x95, 0x2f, 0xb5, 0xc6, 0x03, 0x54, 0xb9, 0xe6, 0x32, 0xc2, 0xfb, 0x34, 0xbb, 0x93,
	0x16, 0x25, 0xe8, 0x60, 0x5d, 0xc2, 0xdd, 0xa0, 0x93, 0xdd, 0x87, 0xd7, 0xcf, 0xc7, 0x7f, 0x55,
	0xfc, 0xdf, 0xd7, 0x6b, 0xfb, 0x08, 0xd5, 0xfa, 0x4c, 0x88, 0x11, 0x88, 0x10, 0x37, 0xe8, 0xdf,
	0xef, 0xa4, 0x45, 0x43, 0xb7, 0xb9, 0x81, 0xa4, 0x9a, 0x60, 0x9b, 0xb7, 0x83, 0x91, 0x1f, 0x30,
	0x21, 0x6e, 0x53, 0x10, 0x61, 0xaf, 0xb9, 0x78, 0xf7, 0x9c, 0xc5, 0xca, 0x73, 0x5e, 0x56, 0x9e,
	0xf3, 0xb6, 0xf2, 0x9c, 0xa7, 0x0f, 0xcf, 0xb9, 0x29, 0x33, 0xcd, 0xc7, 0x5b, 0xf6, 0x9c, 0xf3,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xb1, 0x72, 0xfc, 0xc5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	CallSelf(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) CallSelf(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/CallSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
type AppServer interface {
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	CallSelf(context.Context, *HelloReq) (*HelloResp, error)
}

// UnimplementedAppServer can be embedded to have forward compatible implementations.
type UnimplementedAppServer struct {
}

func (*UnimplementedAppServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedAppServer) CallSelf(ctx context.Context, req *HelloReq) (*HelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallSelf not implemented")
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_CallSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CallSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/CallSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CallSelf(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.service.v1.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _App_Ping_Handler,
		},
		{
			MethodName: "CallSelf",
			Handler:    _App_CallSelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
