// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" form:"name" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

type HelloResp struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"content"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResp) Reset()         { *m = HelloResp{} }
func (m *HelloResp) String() string { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()    {}
func (*HelloResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *HelloResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResp.Unmarshal(m, b)
}
func (m *HelloResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResp.Marshal(b, m, deterministic)
}
func (m *HelloResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResp.Merge(m, src)
}
func (m *HelloResp) XXX_Size() int {
	return xxx_messageInfo_HelloResp.Size(m)
}
func (m *HelloResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResp proto.InternalMessageInfo

type SayResp struct {
	Db                   *SayResp_DbMsg       `protobuf:"bytes,1,opt,name=Db,proto3" json:"db"`
	Es                   *SayResp_EsMsg       `protobuf:"bytes,2,opt,name=Es,proto3" json:"es"`
	Redis                string               `protobuf:"bytes,3,opt,name=Redis,proto3" json:"redis"`
	Jrpc                 *SayResp_JrpcMsg     `protobuf:"bytes,4,opt,name=Jrpc,proto3" json:"jrpc"`
	Client               *SayResp_CallSelfMsg `protobuf:"bytes,5,opt,name=Client,proto3" json:"client"`
	Hbase                [][]byte             `protobuf:"bytes,6,rep,name=Hbase,proto3" json:"hbase"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SayResp) Reset()         { *m = SayResp{} }
func (m *SayResp) String() string { return proto.CompactTextString(m) }
func (*SayResp) ProtoMessage()    {}
func (*SayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *SayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResp.Unmarshal(m, b)
}
func (m *SayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResp.Marshal(b, m, deterministic)
}
func (m *SayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResp.Merge(m, src)
}
func (m *SayResp) XXX_Size() int {
	return xxx_messageInfo_SayResp.Size(m)
}
func (m *SayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResp.DiscardUnknown(m)
}

var xxx_messageInfo_SayResp proto.InternalMessageInfo

type SayResp_DbMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayResp_DbMsg) Reset()         { *m = SayResp_DbMsg{} }
func (m *SayResp_DbMsg) String() string { return proto.CompactTextString(m) }
func (*SayResp_DbMsg) ProtoMessage()    {}
func (*SayResp_DbMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2, 0}
}
func (m *SayResp_DbMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResp_DbMsg.Unmarshal(m, b)
}
func (m *SayResp_DbMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResp_DbMsg.Marshal(b, m, deterministic)
}
func (m *SayResp_DbMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResp_DbMsg.Merge(m, src)
}
func (m *SayResp_DbMsg) XXX_Size() int {
	return xxx_messageInfo_SayResp_DbMsg.Size(m)
}
func (m *SayResp_DbMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResp_DbMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SayResp_DbMsg proto.InternalMessageInfo

type SayResp_EsMsg struct {
	ClusterName                 string   `protobuf:"bytes,1,opt,name=ClusterName,proto3" json:"cluster_name"`
	Status                      string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"status"`
	TimedOut                    bool     `protobuf:"varint,3,opt,name=TimedOut,proto3" json:"timed_out"`
	NumberOfNodes               float64  `protobuf:"fixed64,4,opt,name=NumberOfNodes,proto3" json:"number_of_nodes"`
	NumberOfDataNodes           float64  `protobuf:"fixed64,5,opt,name=NumberOfDataNodes,proto3" json:"number_of_data_nodes"`
	ActivePrimaryShards         float64  `protobuf:"fixed64,6,opt,name=ActivePrimaryShards,proto3" json:"active_primary_shards"`
	ActiveShards                float64  `protobuf:"fixed64,7,opt,name=ActiveShards,proto3" json:"active_shards"`
	RelocatingShards            float64  `protobuf:"fixed64,8,opt,name=RelocatingShards,proto3" json:"relocating_shards"`
	InitializingShards          float64  `protobuf:"fixed64,9,opt,name=InitializingShards,proto3" json:"initializing_shards"`
	UnassignedShards            float64  `protobuf:"fixed64,10,opt,name=UnassignedShards,proto3" json:"unassigned_shards"`
	DelayedUnassignedShards     float64  `protobuf:"fixed64,11,opt,name=DelayedUnassignedShards,proto3" json:"delayed_unassigned_shards"`
	NumberOfPendingTasks        float64  `protobuf:"fixed64,12,opt,name=NumberOfPendingTasks,proto3" json:"number_of_pending_tasks"`
	NumberOfInFlightFetch       float64  `protobuf:"fixed64,13,opt,name=NumberOfInFlightFetch,proto3" json:"number_of_in_flight_fetch"`
	TaskMaxWaitingInQueue       string   `protobuf:"bytes,14,opt,name=TaskMaxWaitingInQueue,proto3" json:"task_max_waiting_in_queue"`
	TaskMaxWaitingInQueueMillis float64  `protobuf:"fixed64,15,opt,name=TaskMaxWaitingInQueueMillis,proto3" json:"task_max_waiting_in_queue_millis"`
	ActiveShardsPercent         string   `protobuf:"bytes,16,opt,name=ActiveShardsPercent,proto3" json:"active_shards_percent"`
	ActiveShardsPercentAsNumber float64  `protobuf:"fixed64,17,opt,name=ActiveShardsPercentAsNumber,proto3" json:"active_shards_percent_as_number"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *SayResp_EsMsg) Reset()         { *m = SayResp_EsMsg{} }
func (m *SayResp_EsMsg) String() string { return proto.CompactTextString(m) }
func (*SayResp_EsMsg) ProtoMessage()    {}
func (*SayResp_EsMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2, 1}
}
func (m *SayResp_EsMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResp_EsMsg.Unmarshal(m, b)
}
func (m *SayResp_EsMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResp_EsMsg.Marshal(b, m, deterministic)
}
func (m *SayResp_EsMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResp_EsMsg.Merge(m, src)
}
func (m *SayResp_EsMsg) XXX_Size() int {
	return xxx_messageInfo_SayResp_EsMsg.Size(m)
}
func (m *SayResp_EsMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResp_EsMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SayResp_EsMsg proto.InternalMessageInfo

type SayResp_JrpcMsg struct {
	Jsonrpc              string                              `protobuf:"bytes,1,opt,name=Jsonrpc,proto3" json:"jsonrpc"`
	Result               map[string]*SayResp_JrpcMsgLanguage `protobuf:"bytes,2,rep,name=Result,proto3" json:"result" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *SayResp_JrpcMsg) Reset()         { *m = SayResp_JrpcMsg{} }
func (m *SayResp_JrpcMsg) String() string { return proto.CompactTextString(m) }
func (*SayResp_JrpcMsg) ProtoMessage()    {}
func (*SayResp_JrpcMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2, 2}
}
func (m *SayResp_JrpcMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResp_JrpcMsg.Unmarshal(m, b)
}
func (m *SayResp_JrpcMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResp_JrpcMsg.Marshal(b, m, deterministic)
}
func (m *SayResp_JrpcMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResp_JrpcMsg.Merge(m, src)
}
func (m *SayResp_JrpcMsg) XXX_Size() int {
	return xxx_messageInfo_SayResp_JrpcMsg.Size(m)
}
func (m *SayResp_JrpcMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResp_JrpcMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SayResp_JrpcMsg proto.InternalMessageInfo

type SayResp_JrpcMsgLanguage struct {
	En                   string   `protobuf:"bytes,1,opt,name=En,proto3" json:"en"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayResp_JrpcMsgLanguage) Reset()         { *m = SayResp_JrpcMsgLanguage{} }
func (m *SayResp_JrpcMsgLanguage) String() string { return proto.CompactTextString(m) }
func (*SayResp_JrpcMsgLanguage) ProtoMessage()    {}
func (*SayResp_JrpcMsgLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2, 2, 1}
}
func (m *SayResp_JrpcMsgLanguage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResp_JrpcMsgLanguage.Unmarshal(m, b)
}
func (m *SayResp_JrpcMsgLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResp_JrpcMsgLanguage.Marshal(b, m, deterministic)
}
func (m *SayResp_JrpcMsgLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResp_JrpcMsgLanguage.Merge(m, src)
}
func (m *SayResp_JrpcMsgLanguage) XXX_Size() int {
	return xxx_messageInfo_SayResp_JrpcMsgLanguage.Size(m)
}
func (m *SayResp_JrpcMsgLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResp_JrpcMsgLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_SayResp_JrpcMsgLanguage proto.InternalMessageInfo

type SayResp_CallSelfMsg struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"content"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayResp_CallSelfMsg) Reset()         { *m = SayResp_CallSelfMsg{} }
func (m *SayResp_CallSelfMsg) String() string { return proto.CompactTextString(m) }
func (*SayResp_CallSelfMsg) ProtoMessage()    {}
func (*SayResp_CallSelfMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2, 3}
}
func (m *SayResp_CallSelfMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResp_CallSelfMsg.Unmarshal(m, b)
}
func (m *SayResp_CallSelfMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResp_CallSelfMsg.Marshal(b, m, deterministic)
}
func (m *SayResp_CallSelfMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResp_CallSelfMsg.Merge(m, src)
}
func (m *SayResp_CallSelfMsg) XXX_Size() int {
	return xxx_messageInfo_SayResp_CallSelfMsg.Size(m)
}
func (m *SayResp_CallSelfMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResp_CallSelfMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SayResp_CallSelfMsg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HelloReq)(nil), "app.framework.v1.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "app.framework.v1.HelloResp")
	proto.RegisterType((*SayResp)(nil), "app.framework.v1.SayResp")
	proto.RegisterType((*SayResp_DbMsg)(nil), "app.framework.v1.SayResp.DbMsg")
	proto.RegisterType((*SayResp_EsMsg)(nil), "app.framework.v1.SayResp.EsMsg")
	proto.RegisterType((*SayResp_JrpcMsg)(nil), "app.framework.v1.SayResp.JrpcMsg")
	proto.RegisterMapType((map[string]*SayResp_JrpcMsgLanguage)(nil), "app.framework.v1.SayResp.JrpcMsg.ResultEntry")
	proto.RegisterType((*SayResp_JrpcMsgLanguage)(nil), "app.framework.v1.SayResp.JrpcMsg.language")
	proto.RegisterType((*SayResp_CallSelfMsg)(nil), "app.framework.v1.SayResp.CallSelfMsg")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0x4d, 0x73, 0xdb, 0x44,
	0x18, 0xc7, 0x13, 0xf9, 0x7d, 0xed, 0xd0, 0x64, 0xfb, 0xa6, 0x38, 0x25, 0x0a, 0x2a, 0x9d, 0x29,
	0xcc, 0xd4, 0x1e, 0x02, 0x4c, 0xa1, 0x33, 0x0c, 0xe4, 0xc5, 0xa1, 0x0e, 0x93, 0x97, 0xae, 0xcb,
	0x64, 0x86, 0x8b, 0x66, 0x6d, 0xad, 0x95, 0x6d, 0xe4, 0x95, 0xa2, 0x5d, 0xa5, 0x35, 0x47, 0x3e,
	0x00, 0x17, 0x2e, 0x9c, 0xf9, 0x34, 0x3d, 0x76, 0x86, 0xbb, 0x06, 0x02, 0x27, 0xdd, 0xe0, 0x13,
	0x30, 0xbb, 0x2b, 0xc7, 0x6e, 0x63, 0x27, 0xdc, 0xac, 0xe7, 0xff, 0xff, 0xff, 0xf2, 0xec, 0xb3,
	0xd1, 0xae, 0x40, 0x05, 0x87, 0xb4, 0x11, 0x46, 0x81, 0x08, 0xe0, 0x22, 0x0e, 0xc3, 0x46, 0x3f,
	0xc2, 0x03, 0xf2, 0x32, 0x88, 0x4e, 0x1a, 0x67, 0x9f, 0xd4, 0x1f, 0x79, 0x54, 0x1c, 0xc7, 0xdd,
	0x46, 0x2f, 0x18, 0x34, 0xbd, 0xc0, 0x0b, 0x9a, 0xca, 0xd8, 0x8d, 0xfb, 0xea, 0x49, 0x3d, 0xa8,
	0x5f, 0x1a, 0x50, 0x5f, 0xf1, 0x82, 0xc0, 0xf3, 0xc9, 0xd8, 0x45, 0x06, 0xa1, 0x18, 0x66, 0xe2,
	0xbd, 0x4c, 0xc4, 0x21, 0x6d, 0x62, 0xc6, 0x02, 0x81, 0x05, 0x0d, 0x18, 0xd7, 0xaa, 0xbd, 0x05,
	0xca, 0x4f, 0x89, 0xef, 0x07, 0x88, 0x9c, 0xc2, 0xc7, 0x20, 0xbf, 0x8f, 0x07, 0xc4, 0x9c, 0x5f,
	0x9b, 0x7f, 0x58, 0xd9, 0xbc, 0xff, 0x6f, 0x62, 0x59, 0xfd, 0x20, 0x1a, 0x3c, 0xb1, 0x19, 0x1e,
	0x10, 0x7b, 0xed, 0x0c, 0xfb, 0xd4, 0xc5, 0x82, 0x3c, 0xb1, 0x23, 0x72, 0x1a, 0xd3, 0x88, 0xb8,
	0x36, 0x52, 0x01, 0x7b, 0x1d, 0x54, 0x32, 0x08, 0x0f, 0xe1, 0x03, 0x50, 0xda, 0x0a, 0x98, 0x20,
	0x4c, 0x64, 0xa0, 0x6a, 0x9a, 0x58, 0xa5, 0x9e, 0x2e, 0xa1, 0x91, 0x66, 0xff, 0x76, 0x03, 0x94,
	0x3a, 0x78, 0xa8, 0x22, 0x8f, 0x81, 0xb1, 0xdd, 0x55, 0xee, 0xea, 0xba, 0xd5, 0x78, 0x77, 0x1a,
	0x8d, 0xcc, 0xd6, 0xd8, 0xee, 0xee, 0x71, 0x6f, 0xb3, 0x98, 0x26, 0x96, 0xe1, 0x76, 0x91, 0xb1,
	0xdd, 0x95, 0xc1, 0x16, 0x37, 0x8d, 0xeb, 0x82, 0x2d, 0x7e, 0x11, 0x24, 0x1c, 0x19, 0x2d, 0x0e,
	0x2d, 0x50, 0x40, 0xc4, 0xa5, 0xdc, 0xcc, 0xa9, 0x16, 0x2b, 0x69, 0x62, 0x15, 0x22, 0x59, 0x40,
	0xba, 0x0e, 0xbf, 0x06, 0xf9, 0xdd, 0x28, 0xec, 0x99, 0x79, 0xc5, 0xfe, 0x60, 0x36, 0x5b, 0xba,
	0x24, 0xbd, 0x9c, 0x26, 0x56, 0xfe, 0x45, 0x14, 0xf6, 0x90, 0x0a, 0xc2, 0x36, 0x28, 0x6e, 0xf9,
	0x54, 0x4e, 0xa1, 0xa0, 0x10, 0x0f, 0x66, 0x23, 0xb6, 0xb0, 0xef, 0x77, 0x88, 0xdf, 0x97, 0x18,
	0x90, 0x26, 0x56, 0xb1, 0xa7, 0x82, 0x28, 0x03, 0xc8, 0x66, 0x9f, 0x76, 0x31, 0x27, 0x66, 0x71,
	0x2d, 0xf7, 0xb0, 0xa6, 0x9b, 0x3d, 0x96, 0x05, 0xa4, 0xeb, 0xf5, 0xaf, 0x40, 0x41, 0xcd, 0x06,
	0xde, 0x01, 0x46, 0xdb, 0x55, 0x83, 0xcc, 0xe9, 0xe5, 0x52, 0x17, 0x19, 0x6d, 0x17, 0xde, 0xcb,
	0x76, 0xd6, 0x50, 0xab, 0x55, 0xad, 0xca, 0x3d, 0xd5, 0xdb, 0x57, 0x7f, 0x53, 0x01, 0x05, 0x35,
	0x22, 0xb8, 0x0e, 0xaa, 0x5b, 0x7e, 0xcc, 0x05, 0x89, 0x26, 0xfe, 0x11, 0x16, 0xd3, 0xc4, 0xaa,
	0xf5, 0x74, 0xd9, 0x51, 0xb1, 0x49, 0x13, 0xb4, 0x41, 0xb1, 0x23, 0xb0, 0x88, 0x79, 0x46, 0x57,
	0x2b, 0xe0, 0xaa, 0x82, 0x32, 0x05, 0x7e, 0x04, 0xca, 0xcf, 0xe9, 0x80, 0xb8, 0x07, 0xb1, 0x50,
	0x13, 0x2f, 0x6f, 0x2e, 0xa4, 0x89, 0x55, 0x11, 0xb2, 0xe6, 0x04, 0xb1, 0x40, 0x17, 0x32, 0xfc,
	0x12, 0x2c, 0xec, 0xc7, 0x83, 0x2e, 0x89, 0x0e, 0xfa, 0xfb, 0x81, 0x4b, 0xb8, 0xda, 0x81, 0xf9,
	0xcd, 0x9b, 0x69, 0x62, 0xdd, 0x60, 0x4a, 0x70, 0x82, 0xbe, 0xc3, 0xa4, 0x84, 0xde, 0x76, 0xc2,
	0x1d, 0xb0, 0x34, 0x2a, 0x6c, 0x63, 0x81, 0x75, 0xbc, 0xa0, 0xe2, 0x66, 0x9a, 0x58, 0xb7, 0xc6,
	0x71, 0x17, 0x0b, 0x9c, 0x31, 0x2e, 0x47, 0xe0, 0x77, 0xe0, 0xe6, 0x46, 0x4f, 0xd0, 0x33, 0x72,
	0x18, 0xd1, 0x01, 0x8e, 0x86, 0x9d, 0x63, 0x1c, 0xb9, 0xdc, 0x2c, 0x2a, 0xd2, 0x72, 0x9a, 0x58,
	0xb7, 0xb1, 0x92, 0x9d, 0x50, 0xeb, 0x0e, 0x57, 0x06, 0x34, 0x2d, 0x05, 0x3f, 0x07, 0x35, 0x5d,
	0xce, 0x28, 0x25, 0x45, 0x59, 0x4a, 0x13, 0x6b, 0x21, 0xa3, 0x64, 0xe9, 0xb7, 0x6c, 0x70, 0x03,
	0x2c, 0x22, 0xe2, 0x07, 0x3d, 0x2c, 0x28, 0xf3, 0xb2, 0x68, 0x59, 0x45, 0x6f, 0xa7, 0x89, 0xb5,
	0x14, 0x5d, 0x68, 0xa3, 0xf8, 0x25, 0x3b, 0xfc, 0x16, 0xc0, 0x36, 0xa3, 0x82, 0x62, 0x9f, 0xfe,
	0x38, 0x86, 0x54, 0x14, 0xe4, 0x6e, 0x9a, 0x58, 0x37, 0xe9, 0x84, 0x3a, 0xc2, 0x4c, 0x89, 0xc8,
	0x5e, 0xbe, 0x67, 0x98, 0x73, 0xea, 0x31, 0xe2, 0x66, 0x18, 0x30, 0xee, 0x25, 0xbe, 0xd0, 0x2e,
	0x7a, 0x79, 0xd7, 0x0e, 0x8f, 0xc0, 0xdd, 0x6d, 0xe2, 0xe3, 0x21, 0x71, 0x2f, 0x91, 0xaa, 0x8a,
	0xf4, 0x7e, 0x9a, 0x58, 0xcb, 0xae, 0xb6, 0x38, 0x97, 0x89, 0xb3, 0xd2, 0xf0, 0x00, 0xdc, 0x1a,
	0x6d, 0xe0, 0x21, 0x61, 0x2e, 0x65, 0xde, 0x73, 0xcc, 0x4f, 0xb8, 0x59, 0x53, 0xd4, 0x95, 0x34,
	0xb1, 0xee, 0x8e, 0xb7, 0x3d, 0xd4, 0x0e, 0x47, 0x48, 0x0b, 0x9a, 0x1a, 0x84, 0x1d, 0x70, 0x7b,
	0x54, 0x6f, 0xb3, 0x1d, 0x9f, 0x7a, 0xc7, 0x62, 0x87, 0x88, 0xde, 0xb1, 0xb9, 0x30, 0xee, 0x73,
	0x4c, 0xa4, 0xcc, 0xe9, 0x2b, 0x8f, 0xd3, 0x97, 0x26, 0x34, 0x3d, 0x2b, 0xa1, 0x92, 0xbe, 0x87,
	0x5f, 0x1d, 0x61, 0x2a, 0xb7, 0xa8, 0xcd, 0x9e, 0xc5, 0x24, 0x26, 0xe6, 0x7b, 0xea, 0x95, 0x51,
	0x50, 0xd9, 0x94, 0x33, 0xc0, 0xaf, 0x9c, 0x97, 0xda, 0x22, 0xd9, 0xa7, 0xd2, 0x84, 0xa6, 0x67,
	0x61, 0x1f, 0xac, 0x4c, 0x15, 0xf6, 0xa8, 0xef, 0x53, 0x6e, 0xde, 0x50, 0xfd, 0x7e, 0x98, 0x26,
	0xd6, 0xda, 0x4c, 0xb4, 0x33, 0x50, 0x5e, 0x74, 0x15, 0x68, 0xfc, 0x3a, 0xe8, 0x91, 0x1f, 0x92,
	0xa8, 0x27, 0x8f, 0xb5, 0x45, 0xd5, 0xfa, 0xe4, 0xeb, 0xa0, 0xf7, 0xca, 0x09, 0xb5, 0x01, 0x4d,
	0x4b, 0x41, 0x02, 0x56, 0xa6, 0x94, 0x37, 0xb8, 0x9e, 0x9b, 0xb9, 0xa4, 0x9a, 0xbe, 0x9f, 0x26,
	0x96, 0x35, 0x15, 0xea, 0x60, 0xee, 0xe8, 0xe9, 0xa3, 0xab, 0x38, 0xf5, 0x9f, 0x0d, 0x50, 0xca,
	0x4e, 0x66, 0x79, 0x21, 0xed, 0xf2, 0x80, 0xc9, 0xd3, 0x7c, 0xe2, 0x42, 0x7a, 0xa1, 0x4b, 0x68,
	0xa4, 0xc1, 0x67, 0xa0, 0x88, 0x08, 0x8f, 0x7d, 0x61, 0x1a, 0x6b, 0xb9, 0x87, 0xd5, 0xf5, 0x47,
	0xd7, 0x9e, 0xf9, 0x0d, 0xed, 0x6f, 0x31, 0x11, 0x0d, 0xf5, 0xb1, 0x17, 0xa9, 0x02, 0xca, 0x40,
	0x75, 0x02, 0xaa, 0x13, 0x16, 0xb8, 0x08, 0x72, 0x27, 0x64, 0xa8, 0x9b, 0x40, 0xf2, 0x27, 0xfc,
	0x06, 0x14, 0xce, 0xb0, 0x1f, 0x93, 0xec, 0x0a, 0xfb, 0xf8, 0xfa, 0x3f, 0xe9, 0x63, 0xe6, 0xc5,
	0xd8, 0x23, 0x48, 0x07, 0x9f, 0x18, 0x5f, 0xcc, 0xd7, 0x6d, 0x50, 0x1e, 0x95, 0xe5, 0x0d, 0xd0,
	0x62, 0xd9, 0x3a, 0xf5, 0x85, 0xc7, 0x90, 0xd1, 0x62, 0xf5, 0xcf, 0x40, 0x75, 0xe2, 0x9a, 0xf9,
	0x9f, 0x97, 0xf4, 0xfa, 0x3f, 0xf3, 0x20, 0xb7, 0x11, 0x86, 0xb0, 0x05, 0xf2, 0x87, 0x94, 0x79,
	0xf0, 0x4e, 0x43, 0x7f, 0x4c, 0x34, 0x46, 0x5f, 0x1a, 0x8d, 0x96, 0xfc, 0xd2, 0xa8, 0xcf, 0xa8,
	0xdb, 0x0b, 0x3f, 0xfd, 0xfe, 0xf7, 0x2f, 0x46, 0x09, 0x16, 0x9a, 0xa1, 0x8c, 0xef, 0x82, 0x5c,
	0x07, 0x0f, 0x61, 0xfd, 0xf2, 0x32, 0x47, 0xdf, 0x20, 0xf5, 0xe5, 0x99, 0x23, 0xb0, 0x6b, 0x0a,
	0x56, 0x84, 0xf9, 0x26, 0xc7, 0x43, 0x78, 0x04, 0xca, 0xa3, 0x05, 0x5d, 0x09, 0x5c, 0x99, 0xa9,
	0xf1, 0xd0, 0x86, 0x0a, 0x59, 0x83, 0xa0, 0xd9, 0xc3, 0xbe, 0xef, 0x70, 0xe2, 0xf7, 0x37, 0x97,
	0x5f, 0xff, 0xb9, 0x3a, 0xf7, 0xfa, 0x7c, 0x75, 0xee, 0xcd, 0xf9, 0xea, 0xdc, 0x1f, 0xe7, 0xab,
	0x73, 0xbf, 0xfe, 0xb5, 0x3a, 0xf7, 0x43, 0x0e, 0x87, 0xb4, 0x5b, 0x54, 0xcb, 0xfb, 0xf4, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x81, 0x5d, 0x95, 0xbc, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppClient interface {
	// ping
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// say
	Say(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*SayResp, error)
	// call_self
	CallSelf(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/app.framework.v1.App/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Say(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*SayResp, error) {
	out := new(SayResp)
	err := c.cc.Invoke(ctx, "/app.framework.v1.App/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) CallSelf(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, "/app.framework.v1.App/CallSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
type AppServer interface {
	// ping
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	// say
	Say(context.Context, *HelloReq) (*SayResp, error)
	// call_self
	CallSelf(context.Context, *HelloReq) (*HelloResp, error)
}

// UnimplementedAppServer can be embedded to have forward compatible implementations.
type UnimplementedAppServer struct {
}

func (*UnimplementedAppServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedAppServer) Say(ctx context.Context, req *HelloReq) (*SayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (*UnimplementedAppServer) CallSelf(ctx context.Context, req *HelloReq) (*HelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallSelf not implemented")
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.framework.v1.App/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.framework.v1.App/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Say(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_CallSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CallSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.framework.v1.App/CallSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CallSelf(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.framework.v1.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _App_Ping_Handler,
		},
		{
			MethodName: "Say",
			Handler:    _App_Say_Handler,
		},
		{
			MethodName: "CallSelf",
			Handler:    _App_CallSelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
